# Generated by Django 4.2.4 on 2023-08-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('walk_in', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_roles',
            field=models.ManyToManyField(related_name='users', to='walk_in.role'),
        ),
        migrations.AddField(
            model_name='professionalqualification',
            name='expert_skills',
            field=models.ManyToManyField(related_name='expert_skills', to='users.skill'),
        ),
        migrations.AddField(
            model_name='professionalqualification',
            name='familiar_skills',
            field=models.ManyToManyField(related_name='familiar_skills', to='users.skill'),
        ),
    ]
