# Generated by Django 4.2.4 on 2023-08-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalqualification',
            name='expert_skills',
        ),
        migrations.RemoveField(
            model_name='professionalqualification',
            name='familiar_skills',
        ),
        migrations.RemoveField(
            model_name='professionalqualification',
            name='user',
        ),
        migrations.DeleteModel(
            name='EducationalQualification',
        ),
        migrations.DeleteModel(
            name='ProfessionalQualification',
        ),
    ]
