# Generated by Django 4.2.4 on 2023-08-27 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_professionalqualification_expert_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=45)),
                ('experience', models.IntegerField()),
                ('current_ctc', models.CharField(blank=True, max_length=45)),
                ('expected_ctc', models.CharField(blank=True, max_length=45)),
                ('other_skills', models.TextField(blank=True)),
                ('on_notice_period', models.BooleanField()),
                ('notice_period_end', models.DateField(null=True)),
                ('notice_period_duration', models.IntegerField(null=True)),
                ('applied_recently', models.BooleanField()),
                ('applied_role', models.TextField(blank=True)),
                ('expert_skills', models.ManyToManyField(related_name='expert_skills', to='users.skill')),
                ('familiar_skills', models.ManyToManyField(related_name='familiar_skills', to='users.skill')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggregate_percentage', models.SmallIntegerField()),
                ('year_of_passing', models.CharField(max_length=4)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_qualifications', to='users.college')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_qualifications', to='users.degree')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_qualifications', to='users.profile')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_qualifications', to='users.stream')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
