# Generated by Django 4.2.4 on 2023-08-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_professionalqualification_educationalqualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalqualification',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalqualification',
            name='expert_skills',
            field=models.ManyToManyField(blank=True, related_name='expert_skills', to='users.skill'),
        ),
        migrations.AlterField(
            model_name='professionalqualification',
            name='notice_period_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionalqualification',
            name='notice_period_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
