# Generated by Django 4.2.4 on 2023-08-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_professionalqualification_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='portfolio_URL',
            new_name='portfolio_url',
        ),
    ]
