# Generated by Django 4.2.4 on 2023-08-28 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_educationalqualification_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalqualification',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_qualification', to='users.profile'),
        ),
    ]
