# Generated by Django 4.2.4 on 2023-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_professionalqualification_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalqualification',
            name='expert_skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='expert_skills', to='users.skill'),
        ),
    ]
