# Generated by Django 4.2.4 on 2023-08-29 06:26

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_professionalqualification_expert_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to),
        ),
    ]
