# Generated by Django 4.2.4 on 2023-08-29 08:34

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=users.models.file_upload_to),
        ),
    ]
