# Generated by Django 4.2.4 on 2023-08-31 07:20

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_type_professionalqualification_applicant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='address_line_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='professionalqualification',
            name='expert_skills',
            field=models.ManyToManyField(related_name='expert_skills', to='users.skill'),
        ),
        migrations.AlterField(
            model_name='professionalqualification',
            name='on_notice_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=users.models.upload_to),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(null=True, upload_to=users.models.file_upload_to),
        ),
    ]
