# Generated by Django 4.2.4 on 2023-08-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walk_in', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
