# Generated by Django 4.2.4 on 2023-08-22 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walk_in', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('application_last_date', models.DateTimeField()),
                ('general_instructions', models.TextField()),
                ('instructions', models.TextField()),
                ('min_sys_requirements', models.TextField()),
                ('role', models.ManyToManyField(related_name='walk_ins', to='walk_in.role')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_ins', to='walk_in.venue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
