# Generated by Django 4.2.4 on 2023-08-27 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('walk_in', '0002_remove_application_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='slot',
            new_name='slot_end_time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
