# Generated by Django 4.2.4 on 2023-08-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walk_in', '0002_walkin_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walkin',
            old_name='role',
            new_name='roles',
        ),
    ]
