# Generated by Django 4.2.4 on 2023-08-27 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_professionalqualification_educationalqualification'),
        ('walk_in', '0003_rename_slot_timeslot_slot_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='applications', to='users.profile'),
        ),
    ]
