# Generated by Django 4.2.4 on 2023-08-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walk_in', '0004_remove_application_user_application_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
