# Generated by Django 4.2.4 on 2023-08-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk_in', '0007_application_applicant_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='preferred_roles',
        ),
        migrations.AddField(
            model_name='application',
            name='preferred_roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='applications', to='walk_in.role'),
        ),
    ]
